# Generated by Django 4.2.29 on 2026-03-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
