# Generated by Django 4.2.29 on 2026-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_category_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL or embed URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('completion', 'Course Completion'), ('certificate', 'Certificate Issued'), ('quiz_passed', 'Quiz Passed'), ('streak', 'Learning Streak'), ('system', 'System'), ('course_approved', 'Course Approved'), ('course_rejected', 'Course Rejected')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
